theme: jekyll-theme-cayman
github: 
  project_title: FileRegD
  project_tagline: File a RegD for your startup or VC/Real Estate fund. Starting at $999 up to $5K. 
  is_project_page: false
google_analytics: UA-125899912-1
plugins:
  - jemoji
