theme: jekyll-theme-cayman
github: 
  project_title: File RegD
  project_tagline: For fundraising your startup, venture capital or real estate funds. $3K flat fee.
  is_project_page: false
google_analytics: UA-125899912-1
plugins:
  - jemoji
